Document: draco
Title: Debian draco Manual
Author: <insert document author here>
Abstract: This manual describes what draco is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/draco/draco.sgml.gz

Format: postscript
Files: /usr/share/doc/draco/draco.ps.gz

Format: text
Files: /usr/share/doc/draco/draco.text.gz

Format: HTML
Index: /usr/share/doc/draco/html/index.html
Files: /usr/share/doc/draco/html/*.html
